version: 2
updates:
  - package-ecosystem: "github-actions"
    target-branch: v1
    directory: "/"
    schedule:
      interval: "daily"
    labels:
    - dependencies

  - package-ecosystem: "gomod"
    target-branch: v1
    directory: "/"
    schedule:
      interval: "daily"
    labels:
    - dependencies
